# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170804_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
