# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170814_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_content', models.TextField()),
                ('image_content', models.ImageField(blank=True, upload_to='grumblr_photos')),
                ('like', models.IntegerField(default=0)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ManyToManyField(to='users.Comment')),
            ],
        ),
    ]
