# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='\u77e5\u540d\u673a\u6784', max_length=4, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
