# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_courseorg_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='home_img',
            field=models.ImageField(default='1200*800\u5927\u56fe', height_field=800, upload_to='org/%Y/%m', verbose_name='\u4e3b\u9875\u5927\u56fe', width_field=1200),
        ),
    ]
