# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20170909_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '\u827a\u672f\u5bb6', 'verbose_name_plural': '\u827a\u672f\u5bb6'},
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=150, verbose_name='\u827a\u672f\u5bb6\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('hh', '\u7ed8\u753b'), ('dk', '\u96d5\u5851'), ('ty', '\u9676\u827a')], default='hh', max_length=20, verbose_name='\u827a\u672f\u5bb6\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='\u6240\u5728\u57ce\u5e02'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='courses_nums',
            field=models.IntegerField(default=0, verbose_name='\u4f5c\u54c1\u6570'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(verbose_name='\u827a\u672f\u5bb6\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u5173\u6ce8\u6570'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u827a\u672f\u5bb6\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='\u753b\u8005', max_length=4, verbose_name='\u827a\u672f\u5bb6\u6807\u7b7e'),
        ),
    ]
