# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u827a\u672f', max_length=20, verbose_name='\u8bfe\u7a0b\u5217\u8868'),
        ),
    ]
