# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 23:00
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170830_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercourse',
            options={'verbose_name': '\u8f6e\u64ad\u4f5c\u54c1', 'verbose_name_plural': '\u8f6e\u64ad\u4f5c\u54c1'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u4f5c\u54c1', 'verbose_name_plural': '\u4f5c\u54c1'},
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u827a\u672f', max_length=20, verbose_name='\u4f5c\u54c1\u5217\u8868'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u827a\u672f\u5bb6'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('sc', '\u6c34\u5f69'), ('yh', '\u6cb9\u753b'), ('sm', '\u7d20\u63cf'), ('bx', '\u4e19\u70ef'), ('tbh', '\u70ad\u7b14\u753b'), ('smh', '\u6c34\u58a8\u753b'), ('fch', '\u7c89\u5f69\u753b'), ('swys', '\u6570\u4f4d\u827a\u672f'), ('banh', '\u7248\u753b'), ('boh', '\u5e1b\u753b'), ('bih', '\u58c1\u753b')], max_length=20, verbose_name='\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u4f5c\u54c1\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u4f5c\u54c1\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u5173\u6ce8\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u4f5c\u54c1\u7528\u65f6(\u5929)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u4f5c\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u4f5c\u54c1'),
        ),
    ]
